---
  - name: Ensure iterm2 is installed
    homebrew_cask:
      name: iterm2

  - name: Add required homebrew repos
    homebrew_tap:
      name: homebrew/cask-fonts

  - name: Ensure console utils are installed
    homebrew:
      name:
        - ansible-lint
        - bat
        - git
        - yarn

  - name: Ensure graphical utils are installed
    homebrew_cask:
      name:
        - docker
        - chromium
        - java
        - ngrok
        - visual-studio-code
