---
  - name: Ensure my productivity tools are installed
    homebrew_cask:
      name:
        - 1password
        - discord
        - notion
        - skype
        - tor-browser
        - transmission
        - zoomus

  - name: Recuce noise from the macos
    osx_defaults:
      key: "{{ item.key }}"
      domain: "{{ item.domain }}"
      value: "{{ item.value }}"
    loop:
      - domain: com.apple.systempreferences
        key: AttentionPrefBundleIDs
        value: 0
      - domain: com.apple.dock
        key: no-bouncing
        value: TRUE
  - name: Ensure screenshots directory exists
    file:
        path: ~/Documents/screenshots
        state: directory

  - name: Set default screenshots diresctory
    osx_defaults:
      key: "{{ item.key }}"
      domain: "{{ item.domain }}"
      value: "{{ item.value }}"
    loop:
      - domain: com.apple.screencapture
        key: location
        value: ~/Documents/screenshots
